name: Continuous Deployment

on:
    push:
      branches:
        - master

jobs:
  build-and-publish:
    name: Build And Publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET CLI
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
      - name: Test
        run: dotnet test
      - name: Build
        run: dotnet build CancellationTokenAnalyzers --configuration Release
      - name: Publish
        run: dotnet nuget push CancellationTokenAnalyzers/bin/Release/*.nupkg
